# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

# Trigger on every push to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Use Node.js v18
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      # 3) Install dependencies cleanly
      - name: Install dependencies
        run: npm ci

      # 4) Build your Vite site
      - name: Build
        run: npm run build

      # 5) Publish the `dist/` folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
