name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout ALL history and disable persisting credentials
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0               # full history, required for pushing tags/branches
          persist-credentials: false   # so deploy step can use GITHUB_TOKEN

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build your Vite site
      - name: Build site
        run: npm run build

      # 5) Deploy the dist/ folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
